In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("train_titanic.csv")

In [3]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df_titanic = data.drop(["PassengerId","Ticket","Cabin","Name"],axis=1)

In [5]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [6]:
df_titanic["Age"].mean()

29.69911764705882

In [7]:
df_titanic["Age"].fillna(df_titanic["Age"].mean(),inplace=True)

In [8]:
df_titanic

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
df_titanic = pd.get_dummies(df_titanic,columns=['Sex','Embarked'])

In [11]:
df_titanic.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,False,True,False,False,True
1,1,1,38.0,1,0,71.2833,True,False,True,False,False
2,1,3,26.0,0,0,7.9250,True,False,False,False,True
3,1,1,35.0,1,0,53.1000,True,False,False,False,True
4,0,3,35.0,0,0,8.0500,False,True,False,False,True

In [15]:
df_titanic['Age_Disc'] = df_titanic['Age']
scaler = MinMaxScaler()
df_titanic[['Age','Fare']] = scaler.fit_transform(df_titanic[['Age','Fare']])

In [16]:
df_titanic[['Age','Fare']]

          Age      Fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
886  0.334004  0.025374
887  0.233476  0.058556
888  0.367921  0.045771
889  0.321438  0.058556
890  0.396833  0.015127

[891 rows x 2 columns]

In [18]:
df_titanic['FamilySize'] = df_titanic['SibSp'] + df_titanic['Parch'] +1

In [19]:
df_titanic.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Age_Disc,FamilySize
0,0,3,0.271174,1,0,0.014151,False,True,False,False,True,22.0,2
1,1,1,0.472229,1,0,0.139136,True,False,True,False,False,38.0,2
2,1,3,0.321438,0,0,0.015469,True,False,False,False,True,26.0,1
3,1,1,0.434531,1,0,0.103644,True,False,False,False,True,35.0,2
4,0,3,0.434531,0,0,0.015713,False,True,False,False,True,35.0,1

In [20]:
from sklearn.feature_selection import SelectKBest, chi2

In [23]:
X = df_titanic.drop('Survived',axis=1)
y = df_titanic['Survived']
selector = SelectKBest(chi2,k=4)
X_new = selector.fit_transform(X,y)

In [24]:
X

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Age_Disc,FamilySize
0,3,0.271174,1,0,0.014151,False,True,False,False,True,22.000000,2
1,1,0.472229,1,0,0.139136,True,False,True,False,False,38.000000,2
2,3,0.321438,0,0,0.015469,True,False,False,False,True,26.000000,1
3,1,0.434531,1,0,0.103644,True,False,False,False,True,35.000000,2
4,3,0.434531,0,0,0.015713,False,True,False,False,True,35.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,0.334004,0,0,0.025374,False,True,False,False,True,27.000000,1
887,1,0.233476,0,0,0.058556,True,False,False,False,True,19.000000,1
888,3,0.367921,1,2,0.045771,True,False,False,False,True,29.699118,4
889,1,0.321438,0,0,0.058556,False,True,True,False,False,26.000000,1
890,3,0.396833,0,0,0.015127,False,True,False,True,False,32.000000,1

In [25]:
X_new

array([[ 3.        ,  0.        ,  1.        , 22.        ],
       [ 1.        ,  1.        ,  0.        , 38.        ],
       [ 3.        ,  1.        ,  0.        , 26.        ],
       ...,
       [ 3.        ,  1.        ,  0.        , 29.69911765],
       [ 1.        ,  0.        ,  1.        , 26.        ],
       [ 3.        ,  0.        ,  1.        , 32.        ]])

In [27]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [28]:
selected_features = X.columns[selector.get_support()]
selected_features.tolist()

['Pclass', 'Sex_female', 'Sex_male', 'Age_Disc']

In [30]:
bins = [0,18,30,50,80]
labels = ['Child','Young Adult','Adult','Elderly']
df_titanic['AgeGroup'] = pd.cut(df_titanic['Age_Disc'],bins=bins,labels=labels)

In [31]:
df_titanic.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Age_Disc,FamilySize,AgeGroup
0,0,3,0.271174,1,0,0.014151,False,True,False,False,True,22.0,2,Young Adult
1,1,1,0.472229,1,0,0.139136,True,False,True,False,False,38.0,2,Adult
2,1,3,0.321438,0,0,0.015469,True,False,False,False,True,26.0,1,Young Adult
3,1,1,0.434531,1,0,0.103644,True,False,False,False,True,35.0,2,Adult
4,0,3,0.434531,0,0,0.015713,False,True,False,False,True,35.0,1,Adult

In [32]:
import seaborn as sns 
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error

In [33]:
titanic = sns.load_dataset('titanic')

In [34]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [39]:
titanic.dropna(subset=['age'],inplace=True)

In [40]:
titanic['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: age, Length: 714, dtype: float64

In [41]:
X=titanic['age'].values.reshape(-1,1)
y=titanic['fare']

In [42]:
X

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [31.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [19.  ],
       [40.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [ 3.  ],
       [19.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [45.  ],
       [ 4.  ],
       [29.  ],
       [19.  ],
       [17.  ],
       [26.  ],
       [32.  ],
       [16.  ],
       [21.  ],
       [26.  ],
       [32.  ],
       [25.  ],
       [ 0.83],
       [30.  ],
       [22.  ],
       [29.  ],
       [28.  ],
       [17.  ],
       [33.  ],
       [16.  ],
       [23.  ],
       [24.  ],
       [29.  ],
       [20.  ],
       [46.  ],
       [26.  ],
       [59.  ],
       [71.  ],
       [23.  ],
       [34.  ],
       [34.  ],
       [28.  ],
       [21.  ],
       [33.  ],
       [37.  ],
       [28.  ],
       [21.  ],
       [38.  ],
       [47.  ],
       [14.5 ],
       [22.  ],
       [20.  ],
       [17.  ],
       [21.  ],
       [70.5 ],
       [29.  ],
       [24.  ],
       [ 2.  ],
       [21.  ],
       [32.5 ],
       [32.5 ],
       [54.  ],
       [12.  ],
       [24.  ],
       [45.  ],
       [33.  ],
       [20.  ],
       [47.  ],
       [29.  ],
       [25.  ],
       [23.  ],
       [19.  ],
       [37.  ],
       [16.  ],
       [24.  ],
       [22.  ],
       [24.  ],
       [19.  ],
       [18.  ],
       [19.  ],
       [27.  ],
       [ 9.  ],
       [36.5 ],
       [42.  ],
       [51.  ],
       [22.  ],
       [55.5 ],
       [40.5 ],
       [51.  ],
       [16.  ],
       [30.  ],
       [44.  ],
       [40.  ],
       [26.  ],
       [17.  ],
       [ 1.  ],
       [ 9.  ],
       [45.  ],
       [28.  ],
       [61.  ],
       [ 4.  ],
       [ 1.  ],
       [21.  ],
       [56.  ],
       [18.  ],
       [50.  ],
       [30.  ],
       [36.  ],
       [ 9.  ],
       [ 1.  ],
       [ 4.  ],
       [45.  ],
       [40.  ],
       [36.  ],
       [32.  ],
       [19.  ],
       [19.  ],
       [ 3.  ],
       [44.  ],
       [58.  ],
       [42.  ],
       [24.  ],
       [28.  ],
       [34.  ],
       [45.5 ],
       [18.  ],
       [ 2.  ],
       [32.  ],
       [26.  ],
       [16.  ],
       [40.  ],
       [24.  ],
       [35.  ],
       [22.  ],
       [30.  ],
       [31.  ],
       [27.  ],
       [42.  ],
       [32.  ],
       [30.  ],
       [16.  ],
       [27.  ],
       [51.  ],
       [38.  ],
       [22.  ],
       [19.  ],
       [20.5 ],
       [18.  ],
       [35.  ],
       [29.  ],
       [59.  ],
       [ 5.  ],
       [24.  ],
       [44.  ],
       [ 8.  ],
       [19.  ],
       [33.  ],
       [29.  ],
       [22.  ],
       [30.  ],
       [44.  ],
       [25.  ],
       [24.  ],
       [37.  ],
       [54.  ],
       [29.  ],
       [62.  ],
       [30.  ],
       [41.  ],
       [29.  ],
       [30.  ],
       [35.  ],
       [50.  ],
       [ 3.  ],
       [52.  ],
       [40.  ],
       [36.  ],
       [16.  ],
       [25.  ],
       [58.  ],
       [35.  ],
       [25.  ],
       [41.  ],
       [37.  ],
       [63.  ],
       [45.  ],
       [ 7.  ],
       [35.  ],
       [65.  ],
       [28.  ],
       [16.  ],
       [19.  ],
       [33.  ],
       [30.  ],
       [22.  ],
       [42.  ],
       [22.  ],
       [26.  ],
       [19.  ],
       [36.  ],
       [24.  ],
       [24.  ],
       [23.5 ],
       [ 2.  ],
       [50.  ],
       [19.  ],
       [ 0.92],
       [17.  ],
       [30.  ],
       [30.  ],
       [24.  ],
       [18.  ],
       [26.  ],
       [28.  ],
       [43.  ],
       [26.  ],
       [24.  ],
       [54.  ],
       [31.  ],
       [40.  ],
       [22.  ],
       [27.  ],
       [30.  ],
       [22.  ],
       [36.  ],
       [61.  ],
       [36.  ],
       [31.  ],
       [16.  ],
       [45.5 ],
       [38.  ],
       [16.  ],
       [29.  ],
       [41.  ],
       [45.  ],
       [45.  ],
       [ 2.  ],
       [24.  ],
       [28.  ],
       [25.  ],
       [36.  ],
       [24.  ],
       [40.  ],
       [ 3.  ],
       [42.  ],
       [23.  ],
       [15.  ],
       [25.  ],
       [28.  ],
       [22.  ],
       [38.  ],
       [40.  ],
       [29.  ],
       [45.  ],
       [35.  ],
       [30.  ],
       [60.  ],
       [24.  ],
       [25.  ],
       [18.  ],
       [19.  ],
       [22.  ],
       [ 3.  ],
       [22.  ],
       [27.  ],
       [20.  ],
       [19.  ],
       [42.  ],
       [ 1.  ],
       [32.  ],
       [35.  ],
       [18.  ],
       [ 1.  ],
       [36.  ],
       [17.  ],
       [36.  ],
       [21.  ],
       [28.  ],
       [23.  ],
       [24.  ],
       [22.  ],
       [31.  ],
       [46.  ],
       [23.  ],
       [28.  ],
       [39.  ],
       [26.  ],
       [21.  ],
       [28.  ],
       [20.  ],
       [34.  ],
       [51.  ],
       [ 3.  ],
       [21.  ],
       [33.  ],
       [44.  ],
       [34.  ],
       [18.  ],
       [30.  ],
       [10.  ],
       [21.  ],
       [29.  ],
       [28.  ],
       [18.  ],
       [28.  ],
       [19.  ],
       [32.  ],
       [28.  ],
       [42.  ],
       [17.  ],
       [50.  ],
       [14.  ],
       [21.  ],
       [24.  ],
       [64.  ],
       [31.  ],
       [45.  ],
       [20.  ],
       [25.  ],
       [28.  ],
       [ 4.  ],
       [13.  ],
       [34.  ],
       [ 5.  ],
       [52.  ],
       [36.  ],
       [30.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [50.  ],
       [48.  ],
       [34.  ],
       [47.  ],
       [48.  ],
       [38.  ],
       [56.  ],
       [ 0.75],
       [38.  ],
       [33.  ],
       [23.  ],
       [22.  ],
       [34.  ],
       [29.  ],
       [22.  ],
       [ 2.  ],
       [ 9.  ],
       [50.  ],
       [63.  ],
       [25.  ],
       [35.  ],
       [58.  ],
       [30.  ],
       [ 9.  ],
       [21.  ],
       [55.  ],
       [71.  ],
       [21.  ],
       [54.  ],
       [25.  ],
       [24.  ],
       [17.  ],
       [21.  ],
       [37.  ],
       [16.  ],
       [18.  ],
       [33.  ],
       [28.  ],
       [26.  ],
       [29.  ],
       [36.  ],
       [54.  ],
       [24.  ],
       [47.  ],
       [34.  ],
       [36.  ],
       [32.  ],
       [30.  ],
       [22.  ],
       [44.  ],
       [40.5 ],
       [50.  ],
       [39.  ],
       [23.  ],
       [ 2.  ],
       [17.  ],
       [30.  ],
       [ 7.  ],
       [45.  ],
       [30.  ],
       [22.  ],
       [36.  ],
       [ 9.  ],
       [11.  ],
       [32.  ],
       [50.  ],
       [64.  ],
       [19.  ],
       [33.  ],
       [ 8.  ],
       [17.  ],
       [27.  ],
       [22.  ],
       [22.  ],
       [62.  ],
       [48.  ],
       [39.  ],
       [36.  ],
       [40.  ],
       [28.  ],
       [24.  ],
       [19.  ],
       [29.  ],
       [32.  ],
       [62.  ],
       [53.  ],
       [36.  ],
       [16.  ],
       [19.  ],
       [34.  ],
       [39.  ],
       [32.  ],
       [25.  ],
       [39.  ],
       [54.  ],
       [36.  ],
       [18.  ],
       [47.  ],
       [60.  ],
       [22.  ],
       [35.  ],
       [52.  ],
       [47.  ],
       [37.  ],
       [36.  ],
       [49.  ],
       [49.  ],
       [24.  ],
       [44.  ],
       [35.  ],
       [36.  ],
       [30.  ],
       [27.  ],
       [22.  ],
       [40.  ],
       [39.  ],
       [35.  ],
       [24.  ],
       [34.  ],
       [26.  ],
       [ 4.  ],
       [26.  ],
       [27.  ],
       [42.  ],
       [20.  ],
       [21.  ],
       [21.  ],
       [61.  ],
       [57.  ],
       [21.  ],
       [26.  ],
       [80.  ],
       [51.  ],
       [32.  ],
       [ 9.  ],
       [28.  ],
       [32.  ],
       [31.  ],
       [41.  ],
       [20.  ],
       [24.  ],
       [ 2.  ],
       [ 0.75],
       [48.  ],
       [19.  ],
       [56.  ],
       [23.  ],
       [18.  ],
       [21.  ],
       [18.  ],
       [24.  ],
       [32.  ],
       [23.  ],
       [58.  ],
       [50.  ],
       [40.  ],
       [47.  ],
       [36.  ],
       [20.  ],
       [32.  ],
       [25.  ],
       [43.  ],
       [40.  ],
       [31.  ],
       [70.  ],
       [31.  ],
       [18.  ],
       [24.5 ],
       [18.  ],
       [43.  ],
       [36.  ],
       [27.  ],
       [20.  ],
       [14.  ],
       [60.  ],
       [25.  ],
       [14.  ],
       [19.  ],
       [18.  ],
       [15.  ],
       [31.  ],
       [ 4.  ],
       [25.  ],
       [60.  ],
       [52.  ],
       [44.  ],
       [49.  ],
       [42.  ],
       [18.  ],
       [35.  ],
       [18.  ],
       [25.  ],
       [26.  ],
       [39.  ],
       [45.  ],
       [42.  ],
       [22.  ],
       [24.  ],
       [48.  ],
       [29.  ],
       [52.  ],
       [19.  ],
       [38.  ],
       [27.  ],
       [33.  ],
       [ 6.  ],
       [17.  ],
       [34.  ],
       [50.  ],
       [27.  ],
       [20.  ],
       [30.  ],
       [25.  ],
       [25.  ],
       [29.  ],
       [11.  ],
       [23.  ],
       [23.  ],
       [28.5 ],
       [48.  ],
       [35.  ],
       [36.  ],
       [21.  ],
       [24.  ],
       [31.  ],
       [70.  ],
       [16.  ],
       [30.  ],
       [19.  ],
       [31.  ],
       [ 4.  ],
       [ 6.  ],
       [33.  ],
       [23.  ],
       [48.  ],
       [ 0.67],
       [28.  ],
       [18.  ],
       [34.  ],
       [33.  ],
       [41.  ],
       [20.  ],
       [36.  ],
       [16.  ],
       [51.  ],
       [30.5 ],
       [32.  ],
       [24.  ],
       [48.  ],
       [57.  ],
       [54.  ],
       [18.  ],
       [ 5.  ],
       [43.  ],
       [13.  ],
       [17.  ],
       [29.  ],
       [25.  ],
       [25.  ],
       [18.  ],
       [ 8.  ],
       [ 1.  ],
       [46.  ],
       [16.  ],
       [25.  ],
       [39.  ],
       [49.  ],
       [31.  ],
       [30.  ],
       [30.  ],
       [34.  ],
       [31.  ],
       [11.  ],
       [ 0.42],
       [27.  ],
       [31.  ],
       [39.  ],
       [18.  ],
       [39.  ],
       [33.  ],
       [26.  ],
       [39.  ],
       [35.  ],
       [ 6.  ],
       [30.5 ],
       [23.  ],
       [31.  ],
       [43.  ],
       [10.  ],
       [52.  ],
       [27.  ],
       [38.  ],
       [27.  ],
       [ 2.  ],
       [ 1.  ],
       [62.  ],
       [15.  ],
       [ 0.83],
       [23.  ],
       [18.  ],
       [39.  ],
       [21.  ],
       [32.  ],
       [20.  ],
       [16.  ],
       [30.  ],
       [34.5 ],
       [17.  ],
       [42.  ],
       [35.  ],
       [28.  ],
       [ 4.  ],
       [74.  ],
       [ 9.  ],
       [16.  ],
       [44.  ],
       [18.  ],
       [45.  ],
       [51.  ],
       [24.  ],
       [41.  ],
       [21.  ],
       [48.  ],
       [24.  ],
       [42.  ],
       [27.  ],
       [31.  ],
       [ 4.  ],
       [26.  ],
       [47.  ],
       [33.  ],
       [47.  ],
       [28.  ],
       [15.  ],
       [20.  ],
       [19.  ],
       [56.  ],
       [25.  ],
       [33.  ],
       [22.  ],
       [28.  ],
       [25.  ],
       [39.  ],
       [27.  ],
       [19.  ],
       [26.  ],
       [32.  ]])

In [43]:
y

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
885    29.1250
886    13.0000
887    30.0000
889    30.0000
890     7.7500
Name: fare, Length: 714, dtype: float64

In [44]:
model=LinearRegression()

In [45]:
model.fit(X,y)

LinearRegression()

In [47]:
predictions=model.predict(X)

In [48]:
mse=mean_squared_error(y,predictions)

In [49]:
rmse=np.sqrt(mse)

In [50]:
rmse

52.63727453884735